name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            modules
            tools
            zephyr
            bootloader
            zmk
          key: ${{ runner.os }}-build-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          pip3 install --user -U west
          west init -l config
          west update
          west zephyr-export

      - name: West Build (BLE Micro Pro)
        # ボード名を 'blemicropro' から候補にあった 'ble_micro_pro' に変更します
        run: |
          west build -s zmk/app -b ble_micro_pro -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2