name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            modules
            tools
            zephyr
            bootloader
            zmk
          key: ${{ runner.os }}-build-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          pip3 install --user -U west
          west init -l config
          west update
          west zephyr-export

      - name: Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          tar xvf zephyr-sdk-0.16.8_linux-x86_64_minimal.tar.xz
          cd zephyr-sdk-0.16.8 && ./setup.sh -t arm-zephyr-eabi -c

      - name: West Build (Naked60 on BLE Micro Pro)
        # -b でボード(ble_micro_pro)を指定し、シールド(naked60)を有効にします。
        # ZMK_CONFIGにSHIELDの定義が含まれる場所を指定します。
        run: |
          west build -s zmk/app -b ble_micro_pro -- \
            -DSHIELD=naked60 \
            -DZMK_CONFIG="${GITHUB_WORKSPACE}/config" \
            -DZEPHYR_SDK_INSTALL_DIR=$(pwd)/zephyr-sdk-0.16.8 \
            -DUSER_SHIELD_FACTORY="${GITHUB_WORKSPACE}/boards/shields"
            
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2